# Generated by Django 4.2.7 on 2024-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
