# Generated by Django 4.2.7 on 2024-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0002_alter_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('current_date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=100)),
                ('login_time', models.CharField(max_length=100)),
                ('logout_time', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
