# Generated by Django 4.2.7 on 2024-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='logout_time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
