# Generated by Django 4.2.7 on 2024-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0004_alter_attendance_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punchin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=100)),
                ('empname', models.CharField(max_length=100)),
                ('login_time', models.CharField(max_length=100)),
                ('logout_time', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
