# Generated by Django 4.2.7 on 2024-03-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0006_late_punchin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='late_punchin',
            table='Punchin',
        ),
    ]
