# Generated by Django 4.2.7 on 2024-03-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERMAPP', '0007_alter_late_punchin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='late_punchin',
            table=None,
        ),
    ]
